all:
  children:
    homelab:
      hosts:
        bunsen:
          stack_source: bunsen
          stack_path: "{{ ansible_env.HOME }}"
          stack_rsync_excludes:
            - --exclude=.env
            - --exclude=homeassistant/config/
        gonzo:
          stack_source: gonzo
          stack_path: "{{ ansible_env.HOME }}"
          stack_rsync_excludes:
            - --exclude=.env
            - --exclude=www/
        walter:
          stack_source: walter
          stack_path: /mnt/user/appdata
          stack_rsync_excludes:
            - --exclude=.env
